package com.ajenterprise.paypaybaymax.utils

import androidx.annotation.DrawableRes
import androidx.annotation.StringRes
import com.ajenterprise.paypaybaymax.R
import javax.inject.Inject

class FlagRetriever @Inject constructor() {
    @StringRes
    fun getCurrencySymbol(currency: String): Int? {
        return when (currency) {
            "AFN" -> R.string.currency_afn
            "ARS" -> R.string.currency_ars
            "AWG" -> R.string.currency_awg
            "AUD" -> R.string.currency_aud
            "AZN" -> R.string.currency_azn
            "BSD" -> R.string.currency_bsd
            "BBD" -> R.string.currency_bbd
            "BYN" -> R.string.currency_byn
            "BZD" -> R.string.currency_bzd
            "BMD" -> R.string.currency_bmd
            "BOB" -> R.string.currency_bob
            "BAM" -> R.string.currency_bam
            "BWP" -> R.string.currency_bwp
            "BGN" -> R.string.currency_bgn
            "BRL" -> R.string.currency_brl
            "BND" -> R.string.currency_bnd
            "KHR" -> R.string.currency_khr
            "CAD" -> R.string.currency_cad
            "KYD" -> R.string.currency_kyd
            "CLP" -> R.string.currency_clp
            "CNY" -> R.string.currency_cny
            "COP" -> R.string.currency_cop
            "CRC" -> R.string.currency_crc
            "HRK" -> R.string.currency_hrk
            "CUP" -> R.string.currency_cup
            "CZK" -> R.string.currency_czk
            "DKK" -> R.string.currency_dkk
            "DOP" -> R.string.currency_dop
            "XCD" -> R.string.currency_xcd
            "EGP" -> R.string.currency_egp
            "SVC" -> R.string.currency_svc
            "EUR" -> R.string.currency_eur
            "FKP" -> R.string.currency_fkp
            "FJD" -> R.string.currency_fjd
            "GHS" -> R.string.currency_ghs
            "GIP" -> R.string.currency_gip
            "GTQ" -> R.string.currency_gtq
            "GGP" -> R.string.currency_ggp
            "GYD" -> R.string.currency_gyd
            "HNL" -> R.string.currency_hnl
            "HKD" -> R.string.currency_hkd
            "HUF" -> R.string.currency_huf
            "ISK" -> R.string.currency_isk
            "INR" -> R.string.currency_inr
            "IDR" -> R.string.currency_idr
            "IRR" -> R.string.currency_irr
            "IMP" -> R.string.currency_imp
            "ILS" -> R.string.currency_ils
            "JMD" -> R.string.currency_jmd
            "JPY" -> R.string.currency_jpy
            "JEP" -> R.string.currency_jep
            "KZT" -> R.string.currency_kzt
            "KPW" -> R.string.currency_kpw
            "KRW" -> R.string.currency_krw
            "KGS" -> R.string.currency_kgs
            "LAK" -> R.string.currency_lak
            "LBP" -> R.string.currency_lbp
            "LRD" -> R.string.currency_lrd
            "MKD" -> R.string.currency_mkd
            "MYR" -> R.string.currency_myr
            "MUR" -> R.string.currency_mur
            "MXN" -> R.string.currency_mxn
            "MNT" -> R.string.currency_mnt
            "MZN" -> R.string.currency_mzn
            "NAD" -> R.string.currency_nad
            "NPR" -> R.string.currency_npr
            "ANG" -> R.string.currency_ang
            "NZD" -> R.string.currency_nzd
            "NIO" -> R.string.currency_nio
            "NGN" -> R.string.currency_ngn
            "NOK" -> R.string.currency_nok
            "OMR" -> R.string.currency_omr
            "PKR" -> R.string.currency_pkr
            "PAB" -> R.string.currency_pab
            "PYG" -> R.string.currency_pyg
            "PEN" -> R.string.currency_pen
            "PHP" -> R.string.currency_php
            "PLN" -> R.string.currency_pln
            "QAR" -> R.string.currency_qar
            "RON" -> R.string.currency_ron
            "RUB" -> R.string.currency_rub
            "SHP" -> R.string.currency_shp
            "SAR" -> R.string.currency_sar
            "RSD" -> R.string.currency_rsd
            "SCR" -> R.string.currency_scr
            "SGD" -> R.string.currency_sgd
            "SBD" -> R.string.currency_sbd
            "SOS" -> R.string.currency_sos
            "ZAR" -> R.string.currency_zar
            "LKR" -> R.string.currency_lkr
            "SEK" -> R.string.currency_sek
            "CHF" -> R.string.currency_chf
            "SRD" -> R.string.currency_srd
            "SYP" -> R.string.currency_syp
            "TWD" -> R.string.currency_twd
            "THB" -> R.string.currency_thb
            "TTD" -> R.string.currency_ttd
            "TRY" -> R.string.currency_try
            "TVD" -> R.string.currency_tvd
            "UAH" -> R.string.currency_uah
            "GBP" -> R.string.currency_gbp
            "USD" -> R.string.currency_usd
            "UYU" -> R.string.currency_uyu
            "UZS" -> R.string.currency_uzs
            "VEF" -> R.string.currency_vef
            "VND" -> R.string.currency_vnd
            "YER" -> R.string.currency_yer
            "ZWD" -> R.string.currency_zwd
            else -> null
        }
    }

    @DrawableRes
    fun getDrawable(currency: String): Int {
        return when (currency) {
            "AED" -> R.drawable.ae
            "AFN" -> R.drawable.af
            "ALL" -> R.drawable.al
            "AMD" -> R.drawable.am
            "ANG" -> R.drawable.an
            "AOA" -> R.drawable.ao
            "AQD" -> R.drawable.aq
            "ARS" -> R.drawable.ar
            "AUD" -> R.drawable.au
            "AZN" -> R.drawable.az
            "BAM" -> R.drawable.ba
            "BBD" -> R.drawable.bb
            "BDT" -> R.drawable.bd
            "BGN" -> R.drawable.bg
            "BHD" -> R.drawable.bh
            "BIF" -> R.drawable.bi
            "BMD" -> R.drawable.bm
            "BND" -> R.drawable.bn
            "BOB" -> R.drawable.bo
            "BRL" -> R.drawable.br
            "BSD" -> R.drawable.bs
            "BWP" -> R.drawable.bw
            "BYR" -> R.drawable.by
            "BZD" -> R.drawable.bz
            "CAD" -> R.drawable.ca
            "CDF" -> R.drawable.cd
            "CHF" -> R.drawable.ch
            "CLP" -> R.drawable.cl
            "CNY" -> R.drawable.cn
            "COP" -> R.drawable.co
            "CRC" -> R.drawable.cr
            "CUP" -> R.drawable.cu
            "CVE" -> R.drawable.cv
            "CYP" -> R.drawable.cy
            "CZK" -> R.drawable.cz
            "DJF" -> R.drawable.dj
            "DKK" -> R.drawable.dk
            "DOP" -> R.drawable.dop
            "DZD" -> R.drawable.dz
            "ECS" -> R.drawable.ec
            "EEK" -> R.drawable.ee
            "EGP" -> R.drawable.eg
            "ETB" -> R.drawable.et
            "EUR" -> R.drawable.eu
            "FJD" -> R.drawable.fj
            "FKP" -> R.drawable.fk
            "GBP" -> R.drawable.gb
            "GEL" -> R.drawable.ge
            "GGP" -> R.drawable.gg
            "GHS" -> R.drawable.gh
            "GIP" -> R.drawable.gi
            "GMD" -> R.drawable.gm
            "GNF" -> R.drawable.gn
            "GTQ" -> R.drawable.gt
            "GYD" -> R.drawable.gy
            "HKD" -> R.drawable.hk
            "HNL" -> R.drawable.hn
            "HRK" -> R.drawable.hr
            "HTG" -> R.drawable.ht
            "HUF" -> R.drawable.hu
            "IDR" -> R.drawable.id
            "ILS" -> R.drawable.il
            "INR" -> R.drawable.inr
            "IQD" -> R.drawable.iq
            "IRR" -> R.drawable.ir
            "ISK" -> R.drawable.isk
            "JMD" -> R.drawable.jm
            "JOD" -> R.drawable.jo
            "JPY" -> R.drawable.jp
            "KES" -> R.drawable.ke
            "KGS" -> R.drawable.kg
            "KHR" -> R.drawable.kh
            "KMF" -> R.drawable.km
            "KPW" -> R.drawable.kp
            "KRW" -> R.drawable.kr
            "KWD" -> R.drawable.kw
            "KYD" -> R.drawable.ky
            "KZT" -> R.drawable.kz
            "LAK" -> R.drawable.la
            "LBP" -> R.drawable.lb
            "LKR" -> R.drawable.lk
            "LRD" -> R.drawable.lr
            "LSL" -> R.drawable.ls
            "LTL" -> R.drawable.lt
            "LVL" -> R.drawable.lv
            "LYD" -> R.drawable.ly
            "MAD" -> R.drawable.ma
            "MDL" -> R.drawable.md
            "MGA" -> R.drawable.mg
            "MKD" -> R.drawable.mk
            "MMK" -> R.drawable.mm
            "MNT" -> R.drawable.mn
            "MOP" -> R.drawable.mo
            "MRO" -> R.drawable.mr
            "MTL" -> R.drawable.mt
            "MUR" -> R.drawable.mu
            "MVR" -> R.drawable.mv
            "MWK" -> R.drawable.mw
            "MXN" -> R.drawable.mx
            "MYR" -> R.drawable.my
            "MZN" -> R.drawable.mz
            "NAD" -> R.drawable.na
            "NGN" -> R.drawable.ng
            "NIO" -> R.drawable.ni
            "NOK" -> R.drawable.no
            "NPR" -> R.drawable.np
            "NZD" -> R.drawable.nz
            "OMR" -> R.drawable.om
            "PAB" -> R.drawable.pa
            "PEN" -> R.drawable.pe
            "PGK" -> R.drawable.pg
            "PHP" -> R.drawable.ph
            "PKR" -> R.drawable.pk
            "PLN" -> R.drawable.pl
            "PYG" -> R.drawable.py
            "QAR" -> R.drawable.qa
            "RON" -> R.drawable.ro
            "RSD" -> R.drawable.rs
            "RUB" -> R.drawable.ru
            "RWF" -> R.drawable.rw
            "SAR" -> R.drawable.sa
            "SBD" -> R.drawable.sb
            "SCR" -> R.drawable.sc
            "SDG" -> R.drawable.sd
            "SEK" -> R.drawable.se
            "SGD" -> R.drawable.sg
            "SKK" -> R.drawable.sk
            "SLL" -> R.drawable.sl
            "SOS" -> R.drawable.so
            "SRD" -> R.drawable.sr
            "STD" -> R.drawable.st
            "SVC" -> R.drawable.sv
            "SYP" -> R.drawable.sy
            "SZL" -> R.drawable.sz
            "THB" -> R.drawable.th
            "TJS" -> R.drawable.tj
            "TMT" -> R.drawable.tm
            "TND" -> R.drawable.tn
            "TOP" -> R.drawable.to
            "TRY" -> R.drawable.tr
            "TTD" -> R.drawable.tt
            "TWD" -> R.drawable.tw
            "TZS" -> R.drawable.tz
            "UAH" -> R.drawable.ua
            "UGX" -> R.drawable.ug
            "USD" -> R.drawable.us
            "UYU" -> R.drawable.uy
            "UZS" -> R.drawable.uz
            "VEF" -> R.drawable.ve
            "VND" -> R.drawable.vn
            "VUV" -> R.drawable.vu
            "XAF" -> R.drawable.cf
            "XCD" -> R.drawable.dm
            "XOF" -> R.drawable.ci
            "XPF" -> R.drawable.wf
            "YER" -> R.drawable.ye
            "ZAR" -> R.drawable.za
            "ZMK" -> R.drawable.zm
            "ZWD" -> R.drawable.zw
            else -> R.drawable.ic_launcher_background
        }
    }
}
