package com.ajenterprise.paypaybaymax.utils

import androidx.annotation.DrawableRes
import androidx.annotation.StringRes
import com.ajenterprise.paypaybaymax.R
import javax.inject.Inject

class FlagRetriever @Inject constructor() {
    @DrawableRes
    fun getDrawable(currency: String): Int {
        return when (currency) {
            "AED" -> R.drawable.ae
            "AFN" -> R.drawable.af
            "ALL" -> R.drawable.al
            "AMD" -> R.drawable.am
            "ANG" -> R.drawable.an
            "AOA" -> R.drawable.ao
            "AQD" -> R.drawable.aq
            "ARS" -> R.drawable.ar
            "AUD" -> R.drawable.au
            "AZN" -> R.drawable.az
            "BAM" -> R.drawable.ba
            "BBD" -> R.drawable.bb
            "BDT" -> R.drawable.bd
            "BGN" -> R.drawable.bg
            "BHD" -> R.drawable.bh
            "BIF" -> R.drawable.bi
            "BMD" -> R.drawable.bm
            "BND" -> R.drawable.bn
            "BOB" -> R.drawable.bo
            "BRL" -> R.drawable.br
            "BSD" -> R.drawable.bs
            "BWP" -> R.drawable.bw
            "BYR" -> R.drawable.by
            "BZD" -> R.drawable.bz
            "CAD" -> R.drawable.ca
            "CDF" -> R.drawable.cd
            "CHF" -> R.drawable.ch
            "CLP" -> R.drawable.cl
            "CNY" -> R.drawable.cn
            "COP" -> R.drawable.co
            "CRC" -> R.drawable.cr
            "CUP" -> R.drawable.cu
            "CVE" -> R.drawable.cv
            "CYP" -> R.drawable.cy
            "CZK" -> R.drawable.cz
            "DJF" -> R.drawable.dj
            "DKK" -> R.drawable.dk
            "DOP" -> R.drawable.dop
            "DZD" -> R.drawable.dz
            "ECS" -> R.drawable.ec
            "EEK" -> R.drawable.ee
            "EGP" -> R.drawable.eg
            "ETB" -> R.drawable.et
            "EUR" -> R.drawable.eu
            "FJD" -> R.drawable.fj
            "FKP" -> R.drawable.fk
            "GBP" -> R.drawable.gb
            "GEL" -> R.drawable.ge
            "GGP" -> R.drawable.gg
            "GHS" -> R.drawable.gh
            "GIP" -> R.drawable.gi
            "GMD" -> R.drawable.gm
            "GNF" -> R.drawable.gn
            "GTQ" -> R.drawable.gt
            "GYD" -> R.drawable.gy
            "HKD" -> R.drawable.hk
            "HNL" -> R.drawable.hn
            "HRK" -> R.drawable.hr
            "HTG" -> R.drawable.ht
            "HUF" -> R.drawable.hu
            "IDR" -> R.drawable.id
            "ILS" -> R.drawable.il
            "INR" -> R.drawable.inr
            "IQD" -> R.drawable.iq
            "IRR" -> R.drawable.ir
            "ISK" -> R.drawable.isk
            "JMD" -> R.drawable.jm
            "JOD" -> R.drawable.jo
            "JPY" -> R.drawable.jp
            "KES" -> R.drawable.ke
            "KGS" -> R.drawable.kg
            "KHR" -> R.drawable.kh
            "KMF" -> R.drawable.km
            "KPW" -> R.drawable.kp
            "KRW" -> R.drawable.kr
            "KWD" -> R.drawable.kw
            "KYD" -> R.drawable.ky
            "KZT" -> R.drawable.kz
            "LAK" -> R.drawable.la
            "LBP" -> R.drawable.lb
            "LKR" -> R.drawable.lk
            "LRD" -> R.drawable.lr
            "LSL" -> R.drawable.ls
            "LTL" -> R.drawable.lt
            "LVL" -> R.drawable.lv
            "LYD" -> R.drawable.ly
            "MAD" -> R.drawable.ma
            "MDL" -> R.drawable.md
            "MGA" -> R.drawable.mg
            "MKD" -> R.drawable.mk
            "MMK" -> R.drawable.mm
            "MNT" -> R.drawable.mn
            "MOP" -> R.drawable.mo
            "MRO" -> R.drawable.mr
            "MTL" -> R.drawable.mt
            "MUR" -> R.drawable.mu
            "MVR" -> R.drawable.mv
            "MWK" -> R.drawable.mw
            "MXN" -> R.drawable.mx
            "MYR" -> R.drawable.my
            "MZN" -> R.drawable.mz
            "NAD" -> R.drawable.na
            "NGN" -> R.drawable.ng
            "NIO" -> R.drawable.ni
            "NOK" -> R.drawable.no
            "NPR" -> R.drawable.np
            "NZD" -> R.drawable.nz
            "OMR" -> R.drawable.om
            "PAB" -> R.drawable.pa
            "PEN" -> R.drawable.pe
            "PGK" -> R.drawable.pg
            "PHP" -> R.drawable.ph
            "PKR" -> R.drawable.pk
            "PLN" -> R.drawable.pl
            "PYG" -> R.drawable.py
            "QAR" -> R.drawable.qa
            "RON" -> R.drawable.ro
            "RSD" -> R.drawable.rs
            "RUB" -> R.drawable.ru
            "RWF" -> R.drawable.rw
            "SAR" -> R.drawable.sa
            "SBD" -> R.drawable.sb
            "SCR" -> R.drawable.sc
            "SDG" -> R.drawable.sd
            "SEK" -> R.drawable.se
            "SGD" -> R.drawable.sg
            "SKK" -> R.drawable.sk
            "SLL" -> R.drawable.sl
            "SOS" -> R.drawable.so
            "SRD" -> R.drawable.sr
            "STD" -> R.drawable.st
            "SVC" -> R.drawable.sv
            "SYP" -> R.drawable.sy
            "SZL" -> R.drawable.sz
            "THB" -> R.drawable.th
            "TJS" -> R.drawable.tj
            "TMT" -> R.drawable.tm
            "TND" -> R.drawable.tn
            "TOP" -> R.drawable.to
            "TRY" -> R.drawable.tr
            "TTD" -> R.drawable.tt
            "TWD" -> R.drawable.tw
            "TZS" -> R.drawable.tz
            "UAH" -> R.drawable.ua
            "UGX" -> R.drawable.ug
            "USD" -> R.drawable.us
            "UYU" -> R.drawable.uy
            "UZS" -> R.drawable.uz
            "VEF" -> R.drawable.ve
            "VND" -> R.drawable.vn
            "VUV" -> R.drawable.vu
            "XAF" -> R.drawable.cf
            "XCD" -> R.drawable.dm
            "XOF" -> R.drawable.ci
            "XPF" -> R.drawable.wf
            "YER" -> R.drawable.ye
            "ZAR" -> R.drawable.za
            "ZMK" -> R.drawable.zm
            "ZWD" -> R.drawable.zw
            else -> R.drawable.placeholder
        }
    }
}
